id: P003152
initial_creation_type: ocr
source_metadata:
  id: bdr:W23171
  title: གསུང་ཐོར་བུ། དཀོན་མཆོག་ཐུབ་བསྟན་བསྟན་པའི་རྒྱལ་མཚན།
  author: ''
  volumes:
    8dcda3584b1e4afa928227fdb47fc12d:
      image_group_id: I0377
      title: ''
      volume_number: 1
      total_pages: 586
